### ISSUE TITLE
Moving UX toward one that is like that of SafeDelivery app

### ISSUE THREAD

**Issue by shbucher** [iupui-soic/mHBS_tracker#104]
https://play.google.com/store/apps/details?id=dk.maternity.safedelivery&hl=en 

As mentioned at our scrum meeting on 28 March 2018, for mHBS/DHIS2, I suggest that we emulate the UI/UX of SafeDelivery app, which is a similar type training app, for maternal health, and is targeted toward the same types of end-users and stakeholders as mHBS/DHIS2.  Please download and move through SafeDelivery so that you become familiar with the features and flow. For team members without a personal Android device, please borrow one of the Nexus tablets. Based on initial feedback from our alpha testers, I consider this a high-priority task. By the time we have the beta launch, I really want us to have created a much improved UX for mHBS/DHIS2.

**Comment by sunbiz** [comment]
We have changed the app to use HTML for the digital guide, instead of the PDF. Closing this for now. If there are other UI changes, we can open another issue
