### ISSUE TITLE
Disable rotation in both the apps

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#108]
Both the training and tracker apps, currently rotates into landscape and portrait mode when the mobile is moved. So the rotation should be fixed to stabilize the apps to one orientation

**Comment by sunbiz** [comment]
mHBS training change works only after release build. Commit here -https://github.com/iupui-soic/mHBS_tracker/commit/8c848070e90a062566cdb54c31403ab86c556d9e

mHBS tracker commit here - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/b73a6a9fa3f7054125d9530bba4025d9357b45c2

**Comment by sunbiz** [comment]
It is useful to have the page rotate in the mHBS training app, when the video is playing. Enabled rotation again in the training app through this commit - https://github.com/iupui-soic/mHBS_tracker/commit/7ff2ba302eda244c684e472ccf99fc0e9c705801
