### ISSUE TITLE
Make dynamic checkboxes in the mHBS guide 

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#109]
When a user selects the check box, the option should be evaluated and display the correct answer next to the checkbox in mHBS provider guide

**Comment by sunbiz** [comment]
Committed here - https://github.com/iupui-soic/mHBS_tracker/commit/77b1bf45867c74ce7455234838ebd8e348859529

Might have some other follow-up commits, to fix bugs or save in localstorage.
