### ISSUE TITLE
Hide Logout for mHBS apps

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#113]
Permanently remove the logout option so we can bypass data synchronization issues if the device is not connected to internet

**Comment by sunbiz** [comment]
I think this should be to hide the "logout". The device needs to be connected to the internet for the first time when the facility login is done. Assigning @Premchand95 as was discussed in the last scrum meeting.

**Comment by sunbiz** [comment]
Merged here - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/8768fd792671ad16f6fbcca325ad2a7e44ca21cd

**Comment by sunbiz** [comment]
Closing, as it has been tested and works as expected.
