### ISSUE TITLE
Add internet check

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#117]
Add an internet check before downloading content with function to support showing videos for offline mode.

**Comment by Ezmeyers** [comment]
added this @ https://github.com/Ezmeyers/mHBS_Hybridapp/commit/487895f4fa52825259785af71a28b15e5daf1cc9 

but noticed that it doesn't work if one has connected to internet but not logged in if the wifi requires it so I have to add a check for that still.

**Comment by sunbiz** [comment]
Tested for offline use of the training app. Marking as closed.
