### ISSUE TITLE
adding fabric plugin to cordova to send contentView to server 

### ISSUE THREAD

**Issue by Premchand95** [iupui-soic/mHBS_tracker#119]
added fabric plugin to Cordova application to sent each page contentView to fabric.io, which includes start time, end timestamps, and username

**Comment by Premchand95** [comment]
@Ezmeyers, Please make sure to change the static username to dynamic after merging the code. find the global variable "username" in app.js

**Comment by Ezmeyers** [comment]
@Premchand95 I took care of that in may when I was creating the login :)

**Comment by sunbiz** [comment]
Committed here - https://github.com/iupui-soic/mHBS_tracker/commit/55085ba7a519c362e0bcdd73608081fe774ff5f3
