### ISSUE TITLE
change intent filter on to login receiver on tracker-capture

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#124]
in the manifest on tracker-capture in the login receiver portion the
` <intent-filter><action android:name="edu.iupui.soic.biohealth.plhi.mhbs.activities.SharedLoginActivity"/></intent-filter>`
needs to change to:
`<intent-filter>
   <action android:name="com.example.mHBS.MainActivity"/>
</intent-filter>`
in order to work with the new mhbs app

**Comment by Ezmeyers** [comment]
Closing this, as we discussed we should leave the activity name the same, so I have reverted it back to work with the existing app.

**Comment by sunbiz** [comment]
I guess we will still need to work on modifying this (on the tracker side), so that it can send the correct PIN for the users from the same facility to the training app?

**Comment by Ezmeyers** [comment]
Right now I'm just passing over a hardcoded pin passed with the credentials so I could work on the mHBS side, so that however we modify tracker-capture, then the mHBS training app will at least be ready to handle the incoming pin

**Comment by sunbiz** [comment]
Sounds like a good plan, but I just wanted to keep this issue reopened for that work

**Comment by sunbiz** [comment]
This has been completed here - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/700a7b5e1df12ab766b41f58a0a62ccac3697d75

Tested that all the downloaded entities, when their PIN is in attribute (index 4), then it is correctly sent to the training app
