### ISSUE TITLE
Storage and login issues

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#127]
I believe I fixed these @https://github.com/Ezmeyers/mHBS_Hybridapp/commit/6c6961415faaf7f85455e42bc0c0d4e4c0431627 fixed an issue where app.data wasn't getting initialized, which was causing some problems throughout. I will leave this open until it is tested more.

**Comment by sunbiz** [comment]
This has been tested and so closing it now.
