### ISSUE TITLE
Prepare demo devices

### ISSUE THREAD

**Issue by sunbiz** [iupui-soic/mHBS_tracker#129]
Install the apps on the 3 demo devices:
- S9 (partner apps)
- Google Pixel (partner apps)
- Nexus 7

Install all the mHBS apps on the 20 tablets from Issue #128

**Comment by SherriBucher** [comment]
We need to begin charging and updating these Nexus 7 tablets, ASAP, even while awaiting the delivery of the batteries.  It will take several days to charge, update, and load mHBS.

**Comment by BhavaniSingh** [comment]
Updated the app in S9, charged Nexus tablets and waiting for 4 tablets to get update to latest android version

**Comment by BhavaniSingh** [comment]
Devices are made ready for the research trial.
