### ISSUE TITLE
Quality Improvement Monitoring visit checklist

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#13]
[HB12_QI_Visit_ 2013 03 25.pdf](https://github.com/sivaadde/custom_dhis2_tracker/files/1011288/HB12_QI_Visit_.2013.03.25.pdf)

**Comment by SherriBucher** [comment]
Kalfala, I think you are using an older form above--please use this one:
[mHBB12_QI Visit_v1a_word_28June2017.pdf](https://github.com/iupui-soic/mHBS_tracker/files/1110090/mHBB12_QI.Visit_v1a_word_28June2017.pdf)

**Comment by kalfala** [comment]
The form that I used was the one attached to the ticket that was created,
and did not know that it was outdated. I will go ahead and use the one in
the link that you just sent.

kalfala sannoh

On Wed, Jun 28, 2017 at 4:13 PM, Dr. Sherri Bucher <notifications@github.com

**Comment by SherriBucher** [comment]
Thanks, @kalfala , no problem.
