### ISSUE TITLE
Hide Relationships and Indicators section in mHBS tracker app

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#141]
"Relationship" and "Indicators" section are ambiguous to the user in the data entry screen of mHBS tracker app. Hence, it is necessary to hide them.

**Comment by sunbiz** [comment]
Commit here - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/8c970d8f273e4a57e5f60bc9a3fb2c51419ad49f
