### ISSUE TITLE
Enable profile section to the user in the mHBS tracker app

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#142]
To view the profile section of the enrollment by the user in the mHBS tracker app, it is necessary to enable them in the dhis2

**Comment by sunbiz** [comment]
This seems to be working at the moment for trainee "Lewis Alcindor". Is it because you removed the program rule?

**Comment by BhavaniSingh** [comment]
It might be. This can be confirmed by checking with the recent enrollments. I can discuss with Prem and verify it Professor!

**Comment by BhavaniSingh** [comment]
It seems to be working fine now. I have just checked with Prem. Hence, closing this issue.
