### ISSUE TITLE
Need to edit the ABOUT section and PRIVACY POLICY in the mHBS app

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#144]
According to the edits made by Dr. Bucher, we need to modify the content in the "ABOUT" section and "PRIVACY POLICY" of the mHBS app. Please see the attached document.

[mHBS About and Privacy policy_SB comments (2).docx](https://github.com/iupui-soic/mHBS_tracker/files/2315985/mHBS.About.and.Privacy.policy_SB.comments.2.docx)

**Comment by SherriBucher** [comment]
Thanks, @BhavaniSingh
