### ISSUE TITLE
Error while trying to create a program rule variable in dhis2

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#145]
When I try to create a program rule variable with source type "Tracked Entity Attribute" and save, it doesn't save. Instead, it throws 409 conflict error. Please let me know if any problems in the server side and see the attached copy of the error.

![error](https://user-images.githubusercontent.com/35197945/44549675-d4a86380-a6ef-11e8-9274-87ff3198a2f1.JPG)

**Comment by BhavaniSingh** [comment]
Please upgrade the dhis2 version of 2.27 which was released on 01.06.2017

**Comment by sunbiz** [comment]
DHIS2 has been upgraded to build revision: f76f870 and now the error has been fixed.
