### ISSUE TITLE
Rename the complete and incomplete buttons in the tracker forms

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#149]
We need to rename the "complete button" to "Submit" and "incomplete" to "edit" in tracker forms of mhbs app

**Comment by sunbiz** [comment]
Complete here - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/39cf43bd4fde2722b8ae32a43e785f1bd7aa3468
