### ISSUE TITLE
Collect all the Training Videos to be included in the new app

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#15]

**Comment by kalfala** [comment]
Collect training videos. All training videos to be included in the apps collected. https://www.youtube.com/watch?v=B6jEgEexbEU
https://www.youtube.com/watch?v=PINr6u_VuwY
https://www.youtube.com/watch?v=h-QnKT-moeY
https://www.youtube.com/watch?v=mItAnx0vgcM
https://www.youtube.com/watch?v=fD1766gNRQM
https://www.youtube.com/watch?v=0WhEtCygUJM
https://vimeo.com/80456506
https://vimeo.com/72723118
https://www.youtube.com/watch?v=Rc06nvEgkDs
https://www.lds.org/media-library/video/2011-05-23-neonatal-resuscitation-training-africa?lang=eng

**Comment by Ezmeyers** [comment]
@kalfala https://globalhealthmedia.org/videos/

**Comment by SherriBucher** [comment]
Hi Kalfala--Thanks for your hard work to collect these videos into one place. Many of them are outdated based on the latest neonatal resuscitation evidence-based guideline updates.  The focus of our initial efforts will be to link with the GHM videos in the link that Liz has above, and then with the HBB Facilitator videos you have in the first comment. Please also note, there are videos specifically associated with Helping Babies Breathe, Essential Care for Every Baby, Essential Care for Small Babies, and Helping Mothers Survive. Thanks! Dr. Bucher

**Comment by SherriBucher** [comment]
@sivaadde @kalfala @sunbiz @Ezmeyers  Please also note that **simply connecting with the ORB platform via the mHBS app would be really useful****, as they have lots of evidence-based videos AND PDF materials from our partners such as Maternal and Child Survival Program, Global Health Media, etc  http://health-orb.org/
