### ISSUE TITLE
Rename the "enroll" title in hamburger menu of mhbs tracker app

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#150]
We need to rename "enroll" to "home" and remove the "+" sign beside that in hamburger menu of mhbs tracker app because the option actually just takes us to the home screen.

**Comment by sunbiz** [comment]
Committed here - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/4d552e7129240f92d53dd872e4371187875b9b8a
