### ISSUE TITLE
View and add fields from the existing demographic survey to the profile form

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#157]
Please view the demographic survey from Dr. Rachel and suggest required fields via a word document to "Bhavani Singh" so that he will be adding it to the profile form digitally.

**Comment by BhavaniSingh** [comment]
Sent by Dr. Sherri via mail
[DemographicAndFollowUpSurvey_O.pdf](https://github.com/iupui-soic/mHBS_tracker/files/2399174/DemographicAndFollowUpSurvey_O.pdf)

**Comment by SherriBucher** [comment]
Completed for mHBS/eHBB research tool.  Incorporated into the Profile form.  Screen shots in the mHBS folder on Box. Also see Issue #165
