### ISSUE TITLE
Create the script to add in OSCEs

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#163]
Create the script which will be shown in OSCEs which reflects the performance of the trainee

**Comment by SherriBucher** [comment]
We added a script which provides information on whether the trainee passes/fails, and provide guidance on  what is required to pass each of the HBB 2.0 OSCEs -- both an absolute number of items must be ticked "done," and certain items (with asterisks) MUST be ticked done.  PDFs in issue #40. Some screen shots may also be available in Box folder.
