### ISSUE TITLE
Need to remove functional required fields in OSCEs

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#164]
We need to add asterisk symbol beside the text just to show its mandatory but do not make those as functionally required fields because we don't want the user to be shown that they missed those required fields. 
Reason for the change is we decided the OSCEs to be evaluation tools, not the educational tools in the scrum meeting.

**Comment by SherriBucher** [comment]
This is completed. PDFs of the HBB 2.0 OSCE tools used in the mHBS/eHBB research app are appended to issue #40
