### ISSUE TITLE
Create custom designed assessment, clinical forms in dhis2 and take prints

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#167]
Prem! we cannot take the printout of all the forms such as knowledge check, OSCEs, BMV, delivery checklist etc., that are programmed in the mHBS tracker.
To make those forms into a printable format, we need to custom design those forms in dhis2 as the way they appear in the mobile app. 
The reason for the printouts to look the same way as they look in the mobile app is because the research team needs the forms in the mobile app on paper in the exact same way.

**Comment by SherriBucher** [comment]
Completed, as noted in Issue #40.  Copies of final PDFs found in Issue 40 close out comment.
