### ISSUE TITLE
Import all access credentials information into mHBS

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#175]
Need to get pins/IDs, mail ids etc., from UW and import them into mHBS

**Comment by sunbiz** [comment]
Need to create a Python script that will create a JSON from the csv with the details. Please upload the Python script and the required CSV format that UW needs to send.

Documentation here: https://lists.launchpad.net/dhis2-devs/msg48683.html

**Comment by BhavaniSingh** [comment]
[All_users_final.zip](https://github.com/iupui-soic/mHBS_tracker/files/2776116/All_users_final.zip)
