### ISSUE TITLE
Include HBB 2.0 educational video into mHBS training app

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#176]
There should be only one educational video in the mHBS training app for study purpose. So, have to replace current demo video with HBB 2.0 educational video.

https://www.dropbox.com/s/z8jk9g7pq4q3aw2/HBB-2_RC2.mp4?dl=0

**Comment by Premchand95** [comment]
Committed changes at dedaa2a94eef2dccefaf031b21641d467046d609

**Comment by Premchand95** [comment]
committed latest at https://github.com/Premchand95/mHBS_tracker/commit/a8a599f8a0fb4541c3eb4a8755624b1babdb9b12

**Comment by Premchand95** [comment]
latest commit aa7fe11df856d87766022c15694d787c23e6f3db
