### ISSUE TITLE
harmonize across mHBS, MOO and Busia work flow diagram

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#177]
Need to harmonize all of our tasks according to these three.

**Comment by SherriBucher** [comment]
This has been completed on our end, in terms of ensuring incorporation of harmonized revisions to existing mHBS Tracker tools, and developing new data collection forms, as requested from our collaborators September - December 2018. UW created a job aids file (https://drive.google.com/drive/folders/1HsANz3DPYDuBhN3rrRhuhV0-OZ4NfNky?usp=sharing  ) . UW is responsible for continuing to update the MOO, posting these updated versions in a Google folder, and sending those links to collaborators.
