### ISSUE TITLE
Move DHIS2 to production mode

### ISSUE THREAD

**Issue by BhavaniSingh** [iupui-soic/mHBS_tracker#183]
Step 1: After finalizing that there are no more changes that would be made in DHIS2 server. Export only the relevant elements metadata by removing unnecessary elements such as old data elements using Oxygen XML editor.
Step 2: Use the exported metadata in the DHIS2 server for production mode.

**Comment by sunbiz** [comment]
Move to production has been completed.

The export and import for metadata was causing issues in the program rules and the way in which forms were designed and seen on DHIS2 side.

We finally switched to use a SQL dump using pg_dump (#pg_dump dhis2 > dhis2_backup.sql) for the dhis2 database from the development server and imported the SQL (#psql < dhis2_backup.sql) into the production server. Finally, the mhbs.info domain was pointed to the bmgf.soic.iupui.edu production server and the apache2 letsencrypt renewal was performed using ACME on this new server.

DB Backups can be found here: https://iu.app.box.com/folder/63495383176
A cron script was placed in /etc/cron.d/dhis2_auto_backups to take dump nightly and move to the folder.
