### ISSUE TITLE
Update the mhbs server

### ISSUE THREAD

**Issue by Premchand95** [iupui-soic/mHBS_tracker#188]
the current version of mHBS server cant compatible with latest dhis2 SDK

Update server version to 2.29 or more

**Comment by sunbiz** [comment]
The development server bmgfdev.soic.iupui.edu has been upgraded to 2.31.3.
Notes for upgrade:
  * first upgrade to 2.29 with SQL, then 2.30 with SQL and then automatic upgrade to 2.31.3

Marking the issue as closed.
