### ISSUE TITLE
mHBS tracker option is irresponsive in Navigation drawer.

### ISSUE THREAD

**Issue by satyamsheel** [iupui-soic/mHBS_tracker#192]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/44931142/75606772-4435b500-5b16-11ea-998a-1fea7715842c.gif)

**Comment by prajwal27** [comment]
@satyamsheel It's irresponsive only if the mHBS Tracker Application is not installed. Otherwise, it opens the application on clicking the option. However, I would like to work on this issue.
