### ISSUE TITLE
Links to Viewable mhbs designs-

### ISSUE THREAD

**Issue by tchilders95** [iupui-soic/mHBS_tracker#24]
Taylor Childers Mock Up -
https://marvelapp.com/49j44d3/screen/29355015

**Comment by Ezmeyers** [comment]
[app_design_meyers.pdf](https://github.com/iupui-soic/mHBS_tracker/files/1082188/app_design_meyers.pdf)

Here is the app design #2. It is an interactive pdf, arrows will show where the app pages can be clicked.
