### ISSUE TITLE
Wireframe Prototype 2/High Fidelity Prototype

### ISSUE THREAD

**Issue by tchilders95** [iupui-soic/mHBS_tracker#27]
This is a rough draft created after discussing features and implementation between Liz and I. There are aspects currently missing from this wireframe with odd naming conventions, but the purpose  was to gain better grasp on issues currently present with both our designs and how to remedy them. A high fidelity prototype using google material will take its place tomorrow night on this issues page with more screens,  full prototype functionality, a settings menu with proper navigation, and comments related to the overall principles discussed within usability of the app itself.

https://marvelapp.com/4b4b23b/screen/29790582

**Comment by tchilders95** [comment]
MHBS Prototype High Fidelity Version 1:

https://marvelapp.com/3d3b8fh/screen/29877174

Current problems:
-Currently missing course screens which I will finish tomorrow.
-Will create hamburger menus tomorrow.
-Add Comments to design.

**Comment by SherriBucher** [comment]
Thanks, @tchilders95 , I look forward to hearing/seeing more tomorrow!
