### ISSUE TITLE
Provide LoginReceiver in tracker-capture to send logged in user info to other apps of mHBS suite

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#28]
https://github.com/iupui-soic/dhis2-android-trackercapture needs to be able to listen to requests for login information from other apps and provide them that information, so that the user does not have to login on the apps for a number of times.

Security reminder: Broadcast should only be done to apps from the mHBS suite.

**Comment by jmfranci** [comment]
Created a Login Broadcast sender and a Login Broadcast receiver. Training app receives the broadcast when  a dhis2 login is finished successfully.

**Comment by Ezmeyers** [comment]
@jmfranci can you push your changes with core SDK compilation? I need it for #39 thanks

**Comment by sunbiz** [comment]
Marking as complete. https://github.com/iupui-soic/dhis2-android-trackercapture/commit/3577fd4e4d93b96fe4f656a0ab25380dcf16ae56 Merged.
