### ISSUE TITLE
Links to non-video training materials 

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#29]
We will need some non-video training materials for testing of the app when the time comes (can be from HBB:ECEB/ESCEB/ etc.). Infographics and PDF's will be useful. Additionally, if there are resources tied to training videos we can make a note of that for the courses section.

**Comment by SherriBucher** [comment]
@Ezmeyers @tchilders95 , @sunbiz  and I have discussed that we may want to start, very simply, with linking with 2 existing apps that have already been created by an Indian collaborator and are available via Google play.  

So, have a way within the mHBS powered by DHIS2 app whereby users can simply open up these existing apps for ECEB and ECSB. FYI @sivaadde 

https://play.google.com/store/apps/details?id=com.eceb&hl=en 

https://play.google.com/store/apps/details?id=com.ecsb&hl=en

**Comment by sivaadde** [comment]
@SherriBucher Dr. Bucher the existing mHBS powered by DHIS2 app (tracker capture app) has links to these apps, it can open these apps from it if they are installed on the device.

**Comment by shbucher** [comment]
@sivaadde, great, thanks!!
