### ISSUE TITLE
Provide access to Provider’s Guide for BMV

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#3]
This Information can be obtained from the following Link:
https://www.aap.org/en-us/advocacy-and-policy/aap-health-initiatives/helping-babies-survive/Pages/Course-Materials.aspx
https://www.aap.org/en-us/advocacy-and-policy/aap-health-initiatives/helping-babies-survive/Pages/Instructional-Videos.aspx

**Comment by SherriBucher** [comment]
Here is the file:  

[HBB 2.0 Provider Guide.pdf](https://github.com/iupui-soic/mHBS_tracker/files/1113497/HBB.2.0.Provider.Guide.pdf)

**Comment by sunbiz** [comment]
This has been coded completed in HTML and added to the mHBS Training app as a Guide Tab.
Thus, closing this issue as complete.
