### ISSUE TITLE
Test Video activity on the application

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#30]

**Comment by phoenigmatic** [comment]
AVI
https://drive.google.com/open?id=0B_JCL3n6z6stNmZkUk1KaXp3LW8
WebMD
https://drive.google.com/open?id=0B_JCL3n6z6stbnFpeWVvRmNBLVk

**Comment by sivaadde** [comment]
@tchilders95  You can use these videos which are converted to test.

**Comment by tchilders95** [comment]
AVI is not a supported format as per specified by the android media formats guide:

https://developer.android.com/guide/topics/media/media-formats.html

Please reformat these to a useable format such as .mp4 or .3gp

**Comment by phoenigmatic** [comment]
Can we try the WebM?

**Comment by tchilders95** [comment]
After working with it for today I figured a work around to make WebM work on both downloads and streaming. No worries thanks.
