### ISSUE TITLE
Create PDF Reader

### ISSUE THREAD

**Issue by tchilders95** [iupui-soic/mHBS_tracker#34]
Create PDF Reader

https://marvelapp.com/3d3b8fh/screen/29877175

**Comment by shbucher** [comment]
Hi @tchilders95-- I am excited to see that you are working on this issue!  There are certain HBS educational materials which are presented in pdf format, and which I think will be accessed and utilized by many different types of end-users, once we make them available within the mHBS powered by DHIS2 app.  These include:  Facilitator Flip Charts, Action Plans, and Parents' Guides.  

In particular, I think that digital parents' guides will obtain extremely heavy rotation among both health-facility based and community-based health workers; and, by encouraging all cadres of health workers to download and utilize the mHBS app to use these digital educational guides as they counsel parents and family stakeholders, we can, perhaps, help to standarize and harmonize maternal and newborn health educational activities all along the contiuum of care from the village to the health facility settings.  

I am including the 2 Parent's Guides for ECEB and ESCB below.  If you can use these in your initial development and testing of the pdf reader technology, that would be terrific. These would also be key facets of any mHBS demo that we want to develop.  

Evenutally, in the long term it would be great to embed some interactive functionalities within pdfs such as these...for example, have pop-up screens which summarize the key learning objectives or key health messages, or very short quizzes to test knowledge.  But that is probably for later in the development process. 

Best, Dr. Bucher

[ECSB Parent Guide_Print version_24March2015.pdf](https://github.com/iupui-soic/mHBS_tracker/files/1132461/ECSB.Parent.Guide_Print.version_24March2015.pdf)
[20-07953 HBS ECEB Parent Guide .pdf](https://github.com/iupui-soic/mHBS_tracker/files/1132462/20-07953.HBS.ECEB.Parent.Guide.pdf)

**Comment by shbucher** [comment]
@tchilders95: Here are the Helping Babies Breathe educational materials in pdf format--these probably go under the "Course" tab.

Please note that, the American Academy of Pediatrics already archives all the Helping Babies Survive educational materials, in many languages, at their "international resources" page. Simply linking to this via the mHBS powered by DHIS2 app is much preferable to us duplicating their efforts by uploading a bunch of pdfs to the app. http://internationalresources.aap.org/Resource/Home  

What would add value for us, in terms of mHBS as a digital health tool, is creating interactive functionalities for some of these materials--**ESPECIALLY the Parents' Guides and Action Plans**.  Dr. Saptarshi and I have already started some of this work in regards to the ECEB Action Plan, via a different group of some Boston University students last Spring. There is still a lot of work to be done in terms of that aspect, perhaps by a different SOIC student team.

**Helping Babies Breathe Edition 2 educational materials**:
[HBB 2.0 Flip chart.zip](https://github.com/iupui-soic/mHBS_tracker/files/1132478/HBB.2.0.Flip.chart.zip)
[HBB 2.0 Action Plan.zip](https://github.com/iupui-soic/mHBS_tracker/files/1132480/HBB.2.0.Action.Plan.zip)
[HBB 2.0 Provider Guide.pdf](https://github.com/iupui-soic/mHBS_tracker/files/1132482/HBB.2.0.Provider.Guide.pdf)

**Comment by msjose276** [comment]
I have worked on this issue. I was able to read a pdf from the resources folder "assets". Also, to make the program more flexible, I tried to read pdf from a url but it did not work. I believe it will just take a little more time but I will make it work. Now, I have problems connecting passing the name of the pdf to the new activity but It will not take long.

**Comment by shbucher** [comment]
@msjose276  Thanks. Please update us at the MURI meeting on 07 Dec 2017.  We need to ensure that the PDF readers are working for the BMGF project, as all health care provider groups in Nigeria and Kenya within the RCT will have access, via mHBS/DHIS2, to the PDF of the HBB 2.0 Provider's Guide (link in a previous comment above). Furthermore, we need to ensure that the Research assistants, project coordinators, in-person HBB trainers, etc also will have access, via mHBS/DHIS2, to all 3 of the PDFs, above, for the study. FYI, @Ezmeyers , @sivaadde , @sunbiz

**Comment by Ezmeyers** [comment]
@msjose276  any updates?
