### ISSUE TITLE
Update the current tracker application 

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#35]
DHIS2 has released a latest version of tracker application which has a lot of bug fixes. Update our tracker application to this version. 
Link for the tracker repository ->  https://github.com/dhis2/dhis2-android-trackercapture

**Comment by Ezmeyers** [comment]
will complete this tomorrow thanks @sivaadde for letting us know

**Comment by Ezmeyers** [comment]
I'm not sure how to proceed with this because I'm having multiple issues with the new tracker capture. You can see for yourself by this:

https://github.com/dhis2/dhis2-android-trackercapture/search?utf8=%E2%9C%93&q=getLastEnrollment&type=

As you can see, this function is called, but it does not exist anywhere in the SDK (master, 2.23 legacy, or branch @3f7db1adba which is the commit being used as the default SDK for the new tracker. If it was just this function, it wouldn't be a problem, but it appears there are many functions and resources not found in our SDK or the dhis2-android-sdk that the new tracker capture calls...

**Comment by sivaadde** [comment]
@ezmeyers You have to update the android sdk to the current version.

**Comment by sivaadde** [comment]
@ezmeyers this is the link for sdk https://github.com/dhis2/dhis2-android-sdk
(Just check the tracker capture branch of the sdk which is new sdk )

**Comment by Ezmeyers** [comment]
@sivaadde I have done this. If you search the new SDK there are no functions named "getLastEnrollment" in it. But it's not only this function, there's other pieces not in the new SDK but called by tracker capture...

**Comment by sivaadde** [comment]
@ezmeyers I don't have access to my computer at the moment are you taking about the new sdk folder added to the dhis2 tracker project

**Comment by Ezmeyers** [comment]
@sivaadde 
No; I know that the setup we are using right now is for legacy-2.23 correct? So we have dhis2-android-sdk (legacy-2.23) and dhis2-android-new-sdk (legacy tracker-capture)

Now for the new tracker capture, I made a clean repo to try and get it working with a brand new SDK clone. using the same setup we have (I tried it with both master and legacy). I've tried a combination of many things, however the new tracker app calls functions I simply can't find anywhere even with google hits...

**Comment by sivaadde** [comment]
@ezmeyers this is correct. Try using the source code from the release page. https://github.com/dhis2/dhis2-android-trackercapture/releases

Hope this helps.

**Comment by Ezmeyers** [comment]
@sivaadde Will do thank you!

**Comment by Ezmeyers** [comment]
@sivaadde 

Error:(829, 54) error: cannot find symbol method getLastEnrollment(String,TrackedEntityInstance)
It throws the same error in org.hisp.dhis.android.trackercapture.fragments.programoverview.ProgramOverviewFragment
 that I've been dealing with all weekend. :/

If I create a blank function getLastEnrollment() to get rid of the error, even more functions, resources and even whole classes are called which can't be found. If I add a dummy function called getLastEnrollment it tries to call getEnrollments(x,y,z) but getEnrollments in the SDK is only declared with getEnrollments(x,y) so the parameter inputs don't match. If I fix that..other missing items pop up 30+)

**Comment by Ezmeyers** [comment]
I am working on this migration. We decided to manually add the changes over in the meeting, and this will make the #50 much easier to accomplish. I believe app development in general will go quicker. Git merges when tracker-capture updates will be feasible after this is completed, so this is going to be really great for us.

**Comment by Ezmeyers** [comment]
I've completed the styling updates on the tracker, will add crashlytics tomorrow. Then I'll work on making sure the training app follows this new structure! I've added the keyword "mod:" to comments wherever I made changes on tracker, just to make it easier internally to see changes. Also, I set it up so the SDK doesn't need modification, therefore developers can run the app using submodules if they want. I have made sure to use git submodule deinit --all before pushing, so the submodules are empty when I'm pushing the new tracker to github. Of course, the option to use the SDK in the same folder is available.

**Comment by shbucher** [comment]
Thanks for the updates, @Ezmeyers !  You are doing a great job documenting on Github.  Much appreciation, keep it up!. Dr. Bucher

**Comment by Ezmeyers** [comment]
Added the custom apps to the drawer, that was something I forgot to do. So _now_ crashlytics is next, and then I will work on migrating training to the new format as well.

**Comment by Ezmeyers** [comment]
I just updated tracker to the new version from 2 days ago, handled merge conflicts, and tested that it's working. Crashlytics should be up. I'm working on changing training over

**Comment by sivaadde** [comment]
@Ezmeyers Thank you for the update. Can you also add a link to the new trackercapture repository we have created on the readme page.
