### ISSUE TITLE
Create Knowledge check

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#4]
[Knowledge-Check-HBB-2nd-Edition.pdf](https://github.com/sivaadde/custom_dhis2_tracker/files/942464/Knowledge-Check-HBB-2nd-Edition.pdf)
[Answer-Key-KnowledgeCheck-HBB-2nd-Edition.pdf](https://github.com/sivaadde/custom_dhis2_tracker/files/942474/Answer-Key-KnowledgeCheck-HBB-2nd-Edition.pdf)

1. Create 18 data elements with the required options 
2. Create 72 category options 
3. Match the category options with the appropriate data elements.
4. Should be able to generate score.
5. Create an appropriate program with these questions made available after training.

**Comment by Ezmeyers** [comment]
@tchilders95 question answers need to be changed
