### ISSUE TITLE
Create a Time Widget for inputting time on data entry forms

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#43]
Tracker forms should display a time widget for inputting time data in tracker capture forms.

**Comment by shbucher** [comment]
@sivaadde , thanks for adding this issue, it is a very important one.

**Comment by Premchand95** [comment]
Some one already created time widget, it is working fine.

**Comment by sunbiz** [comment]
I just checked that this was added after we started to use the latest SDK and forked tracker-capture.
Closing the issue as fixed.
