### ISSUE TITLE
Layout render errors in design view

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#49]
Attaching stack traces of rendering errors in layouts. Currently working on this issue. Errors appear when you click design view in layouts folder.
[stacktrace_imgrender.txt](https://github.com/iupui-soic/mHBS_tracker/files/1424799/stacktrace_imgrender.txt)
affects these layouts:

~~fragment_item_list~~
~~content_main~~
~~content_favorites~~
~~app_bar_main~~
~~activity_search~~
~~activity_main~~

**Comment by Ezmeyers** [comment]
@sivaadde I am not sure if this is related to my IDE version can you confirm whether or not you are getting these errors

**Comment by sivaadde** [comment]
@Ezmeyers Is this for the training application or the tracker application, If it's for the tracker application I wouldn't recommend making any changes at this moment.

**Comment by Ezmeyers** [comment]
@sivaade yes it's only for the training app

**Comment by sivaadde** [comment]
@Ezmeyers You can go ahead fix them.

**Comment by Ezmeyers** [comment]
@sivaadde Figured out the issue. Documenting the steps here for future developers on this running into issue. Tracker capture uses com.android.support library version 23.3.0 while training uses 25.3.1. Changing to 23.3.0 on ours is too much of a time sink because our app has 25.3.1 UI features engrained throughout.

Instead, specifying the following before we use our 25.3.1 dependencies in **trainer**'s gradle (_note here: only modifying training app--not anything in tracker!!_), we explicity let the compiler know which version to use (so we choose the one tracker is using) so it doesn't freak out when it hits conflicts with 25.3.1. At the same time, it also allows us to keep using 25.3.1 features 

```
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '23.3.0'
            }
        }
    }
}
```

**Comment by Ezmeyers** [comment]
activity_search has a separate error I'm looking into, the rest are resolved
