### ISSUE TITLE
Create BMV Skill check

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#5]
[BMV-Skills-Check-HBB-2nd-Edition.pdf](https://github.com/sivaadde/custom_dhis2_tracker/files/942491/BMV-Skills-Check-HBB-2nd-Edition.pdf)
1. Create 14 data elements with “yes only” option checkbox. 
2. Create an appropriate program with these questions made available after training. 
3. Should be able to generate score. 

- [ ] Issue 62 is related task and need to be closed and completed before this can be marked as complete

**Comment by Ezmeyers** [comment]
This form has been created with the specified elements. 
I will be doing some testing on the best way to add instructions as the section management doesn't work so well for this.

**Comment by sivaadde** [comment]
- [ ] Data Elements to be changed to Yes Only type.

**Comment by BhavaniSingh** [comment]
BMI checklist is fixed, now it generates appropriate scoring. And every data element is checked and verified in it.
