### ISSUE TITLE
Training app login intent broadcast with tracker capture

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#50]
Add functionality where login intent is checked via broadcast to tracker capture, so when user logs in they can be automatically logged in when opening the training app.

**Comment by Ezmeyers** [comment]
currently working on this feature

**Comment by Ezmeyers** [comment]
I've been working on this, which is actually a bit more complex (to do materialistically) than originally expected. If we pass an intent to tracker capture, this requires modifying tracker capture to allow receiving, checking, and sending a valid flag back to training app. I am thinking making a small library using AIDL and including on both apps may be the most minimal way.

**Comment by sunbiz** [comment]
Making a AIDL library seems like an overkill. Have you tried looking at sharing the userid between the apps?  - https://developer.android.com/guide/topics/manifest/manifest-element.html#uid
And then use SharedPreferences, since that is what is used by the app to store the password in the first place. We will share the same certificate when distributing, so that should be possible.

**Comment by Ezmeyers** [comment]
Alright, I will try that. thanks! I did look at SharedPreferences. Will training always be tied with tracker app? I was thinking about what if the user already has tracker installed, but then there's no way to accomplish this, so they would *have* to have our version. I was still thinking I wasn't able to modify tracker, so I was trying to figure out how to do this. 

One question, isn't sharedUserId tied to the application, but not a specific user? That wont work if multiple people are logging in and out on the same app. I already have a check to make sure tracker is installed-- but trying to figure out how to get the specific user who is logging in.

**Comment by sunbiz** [comment]
The uid is not the same as the DHIS2 user. Its for the underlying linux system that Android uses to run apps. Each app has its own uid. If two apps share the same uid, they can share data too.
So, when a DHIS2 user logs in or out, data is deleted, but the underlying linux user that is used to execute the app is the same.
There is a small caveat, due to a bug in Android, where we have to be careful to keep the uid same, when doing app updates. I cant find the bug# , but its an old and well known bug.

**Comment by Ezmeyers** [comment]
Getting the user information from tracker is not a problem, but the way tracker is set up, the SplashActivity decides whether to set the next activity as login  or main activity based on if a user is logged in. on our app we aren't using a SplashActivity, which is where I ran into difficulties (and I see now why tracker has one). Is it fine to implement SplashActivity on training as well or do you recommend another structure?

**Comment by sunbiz** [comment]
SplashActivity, if it looks good, and helps in branding i.e. differentiate that training is not the same as tracker, then I would like you to add it.
I do not see why it is a necessity. But I also haven't looked at the code in long time. If you think it is necessary and solves this problem, then please do that.

**Comment by Ezmeyers** [comment]
Thanks for your advice. You're right about the splash screen not being necessary. I think keeping tracker having splash screen as the only one makes sense because it's sort of the "main" hub in a way. 

I think I completed this, but I need to double check again to make sure all the cases work. What I found challenging was that, if the user decides to uninstall tracker, or if training is installed before tracker there were some logic errors I had that was causing the login to malfunction. I did end up going with sharedID and that worked great. I will look into that bug you discussed earlier!

Later I will figure out some of the small tasks to be done on training app and make some issues

**Comment by Ezmeyers** [comment]
Okay so there are still issues. I will try to lay out the steps here:
1) User logs into tracker application -> UserAccount object is made, which has the user credentials

2) Now at this point in time, lets say I open training app, and the user has not logged in training app yet.

I have tried:
a)  UserAccount user = MetaDataController.getUserAccount();
user ends up being null.

b) if I try get the the sharedPreferences (credentials), they are null

c) if I try to get the session by calling 
DhisController.getInstance().init();
DhisController.isUserLoggedIn() is false.and
DhisController.getInstance().getSession().getCredentials(); is null

Now, if I re-load the training app, all of these credentials correctly appear. I am guessing I need a way to "force sync" the credentials without having to reload- but I'm not sure how to go about doing that, as nothing I have tried works. If anyone has any thoughts, it is appreciated!

**Comment by Ezmeyers** [comment]
Update: This whole time it was my emulator causing the issue..it does work now. However, there is a login issue happening with tracker app on my end (on master branch, not on the stuff I'm working on). Siva says he's not getting this issue, so it could be my android studio is corrupted and that was the problem the whole time...

**Comment by Ezmeyers** [comment]
@sivaadde I figured it out! I had to add:

 this.AttachBaseContext(sharedContext)
where sharedContext is tracker capture's context!

**Comment by Ezmeyers** [comment]
What I found out:
(From android docs):
1) 
- In order to detect changes in sharedPreferences, such as a user logging in, generally you need to implement:
OnSharedPreferenceChangeListener. 
However, when listening to the shared preferences of another context, you need to keep a local copy, because OnSharedPreferenceChangeListener keeps a weak hash map.
2) After implementing the local shared listener, I found out:
- Shared Preferences does not support multiple processes. 

3) Then I found:
- "You can also set android:process so that components of different applications run in the same process—provided that the applications share the same Linux user ID and are signed with the same certificates."

4) Which I did and confirmed the process share worked, however, the listener still is not picking up yet.

**Comment by Ezmeyers** [comment]
@sivaadde  @sunbiz Although I can get the user credentials in real time now through shared process, I'm not sure if this is viable. Switching between apps after logging in on one causes a process error. Sharing the process for both apps seems nonviable as far as memory? But I'm not that knowledgeable on the intricacies of the process side of android.

**Comment by shbucher** [comment]
@Ezmeyers , thanks for working on this issue. It is a really critical one for our on-going efforts, and I appreciate your tenacity to get it going!

**Comment by Ezmeyers** [comment]
Still waiting to hear back about updated training app from @sivaadde , but also asked him to test the login part I made / get feedback (which is on my github)

**Comment by sivaadde** [comment]
@sunbiz @Ezmeyers DHIS2 doesn't support offline login, I'm not sure how the shared id works when the user is offline.

**Comment by sunbiz** [comment]
@Ezmeyers please address my review comments on PR - https://github.com/iupui-soic/mHBS_tracker/pull/57
I also suggest that you close the current PR, squash your commits into a single one and then send the PR again.

**Comment by Ezmeyers** [comment]
I spent a lot of time trying to squash my commits the other day. I am not sure what I am doing wrong. I was using REBASE -i HEAD~N (where N are the number of previous commits to squash) and then I tagged commits with S to squash those, but every time I would push changes, it started cloning my commits instead changing my commits from like 3 to 12! Clearly I am doing something wrong, but I haven't been able to get squash working correctly, so I may need assistance.

**Comment by sunbiz** [comment]
If I may suggest, please try the GitKraken tool. It's been a revelation lately for how a good GUI can improve productivity. It will let you squash really easily.

**Comment by sunbiz** [comment]
Completed in commit https://github.com/iupui-soic/dhis2-android-trackercapture/commit/3577fd4e4d93b96fe4f656a0ab25380dcf16ae56
This completes the task. Closing the issue as complete.

**Comment by sunbiz** [comment]
There is a long blank screen that shows when transferring from the tracker capture to training v2 hybrid app. So, we will need to add the following:
- [ ] splashscreen back again. 
- [ ] send all the valid PINs through the LoginReceiver

**Comment by sunbiz** [comment]
Sending valid pins from tracker capture - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/700a7b5e1df12ab766b41f58a0a62ccac3697d75

**Comment by sunbiz** [comment]
This has been fixed through Issue #178
