### ISSUE TITLE
Create a  field after 'score' to indicate if trainee passed or not.

### ISSUE THREAD

**Issue by sivaadde** [iupui-soic/mHBS_tracker#55]
This is for all the forms Knowledge Check, OSCE A and OSCE B.

**Comment by shbucher** [comment]
Thanks for setting up this issue, @sivaadde . @phoenigmatic , please also note, it is from these evaluations (listed below) that we will calculate many of the indicators for educational outcomes within the BMGF RCT. (FYI, @sunbiz )

A note that, if possible, scoring algorithms should be automated for each of the forms -- HBB 2nd edition versions. These include:

MCQ (knowledge check; 18 items)
-->To pass:  Learners must sxore 14/18 correct (77%)

BMV checklist (bag-and-mask ventilation checklist; 14 items)
--> To pass: All 14 steps must be ticked "done.

OSCE A (12 items on the existing OSCE A -- however, we may provide a partial scoring mechanism)
--> To pass:  9 out of 12 items ticked "done," AND 3 key items must be ticked done.: These include, prepares and area for ventilation and checjs function of BMV device; dries thoroughly; stimulates breating by rubbing the back.

OSCE B (23 items on existing OSCE B, but we may provide a partial scoring mechanims)
--> To pass: 17 of 23 correct and done must be ticked for 6 key items. These include: stimulates breathing by rubbing the back; chest rise; ventilates at 30-50 breaths per minute; evaluates for breathing and/or chest movement; reapplies mask; repositions head.
