### ISSUE TITLE
knowledge check event not functional in android app

### ISSUE THREAD

**Issue by bhavaniak** [iupui-soic/mHBS_tracker#59]
According to the error evaluated by @sunbiz, it seems that there is a need to change the datatype used (integer) for the events such as knowledge check, to make them functional in android app.

**Comment by bhavaniak** [comment]
I have changed the datatype to a number and applied all the rules to make the knowledge check functional. It works in the web interface, but it needs to be evaluated in android app and check if it throws the same error like before.

**Comment by sunbiz** [comment]
@bhavaniak still does not work in the tracker app. Any other things that you are trying to fix this? Have you got the emulator running for you to test this?

**Comment by bhavaniak** [comment]
@sunbiz yes, it is not working on the mobile app. I have checked it in internet explorer to find the reason for correct functionality in the web interface. 
I have checked it in private window but I couldn't even see any program (mHBS or app usage) in the IE. So couldn't find whether it is the browser capability for the functionality in the web interface. But, I don't think so because if that was the case then these events should have been functional in the browser from starting. I think the possibility of fixing this is, understanding the way the Android code is interpreting program rule, which I am trying to figure out using emulator now.

**Comment by bhavaniak** [comment]
It's not majorly about the datatype but I think expression interpretation is the major factor for this issue.

**Comment by sunbiz** [comment]
@bhavaniak Can you please document how this was fixed, so that we can have fix it when something similar happens?

**Comment by bhavaniak** [comment]
Okay... I will do it ASAP

**Comment by bhavaniak** [comment]
Changed the option set type to text and consequently the data element. In the program rule variable, I have unchecked "use code for optionset"  and then used the correct answer value in program rule expression instead of optionset code value. This fixed the issue.
