### ISSUE TITLE
Add Icons to home buttons on learner tracker

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#75]

**Comment by Ezmeyers** [comment]
@sunbiz  did we still want round backgrounds or is this ok? This is what I have done:

![selection_039](https://user-images.githubusercontent.com/11591786/37629906-cf5bee82-2bb7-11e8-9beb-1a4b43aa0e59.png)

**Comment by sunbiz** [comment]
Looks fine to me

**Comment by Ezmeyers** [comment]
@https://github.com/Ezmeyers/Training-App-Login/commit/38f8dbd84c707c9a8cbad4b54db6b549b0cf5390
