### ISSUE TITLE
Add borders to the reusable list between content items

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#76]

**Comment by Ezmeyers** [comment]
Completed

**Comment by sunbiz** [comment]
Can you please comment the commit SHA before closing issues

**Comment by Ezmeyers** [comment]
@ https://github.com/Ezmeyers/Training-App-Login/commit/1f48cd5b85b5d8e131ead7e8b475a24dfb34a25d
