### ISSUE TITLE
Display single mHBS app in the user's mobile screen

### ISSUE THREAD

**Issue by bhavaniak** [iupui-soic/mHBS_tracker#88]
All the three apps should be clubbed into one app and after the user opens it then the three apps can be displayed inside it so that user can choose the desired one.

**Comment by sunbiz** [comment]
Completed by the following:
#106 - hidden mHBS training icon - https://github.com/iupui-soic/mHBS_tracker/commit/927f8adb15ad6646c40cfab017965a54b5471830
#135 - Change tracker icon to mHBS - https://github.com/iupui-soic/dhis2-android-trackercapture/commit/6e8a039c663f8e310260d97f60fc78e0d332bb33
