### ISSUE TITLE
Add prompts when WiFi is off so that the app displays those prompts

### ISSUE THREAD

**Issue by bhavaniak** [iupui-soic/mHBS_tracker#95]

**Comment by Ezmeyers** [comment]
Added this @https://github.com/Ezmeyers/Training-App-Login/commit/8ff141f571bd2e52faa7c3f97190b255a119cd73 however it is not implement on the download_list in sidebar yet, will do in morning.

**Comment by Ezmeyers** [comment]
completed @ https://github.com/Ezmeyers/Training-App-Login/commit/bdf7d9cbf7911afb5583cb93993a66d202af5496
