### ISSUE TITLE
Create user documentation for mHBS training and tracker

### ISSUE THREAD

**Issue by Ezmeyers** [iupui-soic/mHBS_tracker#99]

**Comment by Ezmeyers** [comment]
working on this @ https://docs.google.com/document/d/12ZO4gTmUiDsCowDClLMHPEB7ptKbpjswRb_iSnLqIn8/edit#

**Comment by Premchand95** [comment]
?

________________________________

**Comment by shbucher** [comment]
[mHBS guide_v1.27March2018.docx](https://github.com/iupui-soic/mHBS_tracker/files/1876360/mHBS.guide_v1.27March2018.docx)

Here is the version of the mHBS guide that was distributed for the initial cycle of alpha-testing on March 26-27, 2019.
